"""initial

Revision ID: 0ee0bd6e2f15
Revises: 
Create Date: 2023-05-13 16:25:31.315519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee0bd6e2f15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('X',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('aircraft_id', sa.String(), nullable=False),
    sa.Column('flight_datetime', sa.DateTime(), nullable=False),
    sa.Column('flight_phase', sa.Enum('TAKEOFF', 'CRUISE', name='flightphase'), nullable=False),
    sa.Column('engine_position', sa.Integer(), nullable=False),
    sa.Column('n1_modifier', sa.Integer(), nullable=False),
    sa.Column('number_blades', sa.Integer(), nullable=False),
    sa.Column('engine_family', sa.String(), nullable=False),
    sa.Column('engine_type', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('ZHPTAC', sa.Float(), nullable=True),
    sa.Column('ZLPTAC', sa.Float(), nullable=True),
    sa.Column('ZPCN12', sa.Float(), nullable=True),
    sa.Column('ZPCN25', sa.Float(), nullable=True),
    sa.Column('ZPHSF', sa.Float(), nullable=True),
    sa.Column('ZPHSR', sa.Float(), nullable=True),
    sa.Column('ZPN12R', sa.Float(), nullable=True),
    sa.Column('ZPOIL', sa.Float(), nullable=True),
    sa.Column('ZPS3', sa.Float(), nullable=True),
    sa.Column('ZT1AB', sa.Float(), nullable=True),
    sa.Column('ZT3', sa.Float(), nullable=True),
    sa.Column('ZT49', sa.Float(), nullable=True),
    sa.Column('ZTAMB', sa.Float(), nullable=True),
    sa.Column('ZTLA', sa.Float(), nullable=True),
    sa.Column('ZTNAC', sa.Float(), nullable=True),
    sa.Column('ZTOIL', sa.Float(), nullable=True),
    sa.Column('ZVB1F', sa.Float(), nullable=True),
    sa.Column('ZVB1R', sa.Float(), nullable=True),
    sa.Column('ZVB2F', sa.Float(), nullable=True),
    sa.Column('ZVB2R', sa.Float(), nullable=True),
    sa.Column('ZVSV', sa.Float(), nullable=True),
    sa.Column('ZWF36', sa.Float(), nullable=True),
    sa.Column('IHPSOV', sa.Integer(), nullable=True),
    sa.Column('aircraft_family', sa.String(), nullable=True),
    sa.Column('aircraft_type', sa.String(), nullable=True),
    sa.Column('aircraft_grp', sa.String(), nullable=True),
    sa.Column('ac_manufacturer', sa.String(), nullable=True),
    sa.Column('AGW', sa.Float(), nullable=True),
    sa.Column('CAS', sa.Float(), nullable=True),
    sa.Column('IAI', sa.Integer(), nullable=True),
    sa.Column('IVS12', sa.Integer(), nullable=True),
    sa.Column('SAT', sa.Float(), nullable=True),
    sa.Column('ZALT', sa.Float(), nullable=True),
    sa.Column('ZT1A', sa.Float(), nullable=True),
    sa.Column('ZVIAS', sa.Float(), nullable=True),
    sa.Column('ZWBP1', sa.Float(), nullable=True),
    sa.Column('ZWBP1_8E', sa.Float(), nullable=True),
    sa.Column('ZWBP2', sa.Float(), nullable=True),
    sa.Column('ZWBP2_8E', sa.Float(), nullable=True),
    sa.Column('ZXM', sa.Float(), nullable=True),
    sa.Column('IBE', sa.Integer(), nullable=True),
    sa.Column('IBP', sa.Integer(), nullable=True),
    sa.Column('IAIE', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_X_aircraft_id'), 'X', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_X_engine_family'), 'X', ['engine_family'], unique=False)
    op.create_index(op.f('ix_X_engine_id'), 'X', ['engine_id'], unique=False)
    op.create_index(op.f('ix_X_engine_type'), 'X', ['engine_type'], unique=False)
    op.create_index(op.f('ix_X_flight_datetime'), 'X', ['flight_datetime'], unique=False)
    op.create_index(op.f('ix_X_flight_phase'), 'X', ['flight_phase'], unique=False)
    op.create_index(op.f('ix_X_id'), 'X', ['id'], unique=False)
    op.create_index(op.f('ix_X_manufacturer'), 'X', ['manufacturer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_X_manufacturer'), table_name='X')
    op.drop_index(op.f('ix_X_id'), table_name='X')
    op.drop_index(op.f('ix_X_flight_phase'), table_name='X')
    op.drop_index(op.f('ix_X_flight_datetime'), table_name='X')
    op.drop_index(op.f('ix_X_engine_type'), table_name='X')
    op.drop_index(op.f('ix_X_engine_id'), table_name='X')
    op.drop_index(op.f('ix_X_engine_family'), table_name='X')
    op.drop_index(op.f('ix_X_aircraft_id'), table_name='X')
    op.drop_table('X')
    # ### end Alembic commands ###
