"""add Y table

Revision ID: 990fffec6de8
Revises: cae75cfce8aa
Create Date: 2023-05-15 15:59:13.637612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990fffec6de8'
down_revision = 'cae75cfce8aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
