"""add Y table

Revision ID: cae75cfce8aa
Revises: 0ee0bd6e2f15
Create Date: 2023-05-15 15:33:45.188855

"""
from alembic import op
import sqlalchemy as sa

from src.models import FlightPhase

# revision identifiers, used by Alembic.
revision = 'cae75cfce8aa'
down_revision = '0ee0bd6e2f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Y',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_datetime', sa.DateTime(), nullable=False),
    sa.Column('flight_phase', sa.dialects.postgresql.ENUM(FlightPhase, create_type=False), nullable=False),
    sa.Column('engine_id', sa.String(), nullable=False),
    sa.Column('BRAT', sa.Float(), nullable=True),
    sa.Column('DEGT', sa.Float(), nullable=True),
    sa.Column('DELFN', sa.Float(), nullable=True),
    sa.Column('DELN1', sa.Float(), nullable=True),
    sa.Column('DELVSV', sa.Float(), nullable=True),
    sa.Column('DPOIL', sa.Float(), nullable=True),
    sa.Column('EGTC', sa.Float(), nullable=True),
    sa.Column('EGTHDM', sa.Float(), nullable=True),
    sa.Column('EGTHDM_D', sa.Float(), nullable=True),
    sa.Column('GEGTMC', sa.Float(), nullable=True),
    sa.Column('GN2MC', sa.Float(), nullable=True),
    sa.Column('GPCN25', sa.Float(), nullable=True),
    sa.Column('GWFM', sa.Float(), nullable=True),
    sa.Column('PCN12', sa.Float(), nullable=True),
    sa.Column('PCN12I', sa.Float(), nullable=True),
    sa.Column('PCN1AR', sa.Float(), nullable=True),
    sa.Column('PCN1BR', sa.Float(), nullable=True),
    sa.Column('PCN1K', sa.Float(), nullable=True),
    sa.Column('PCN2C', sa.Float(), nullable=True),
    sa.Column('SLOATL', sa.Float(), nullable=True),
    sa.Column('SLOATL_D', sa.Float(), nullable=True),
    sa.Column('VSVNOM', sa.Float(), nullable=True),
    sa.Column('WBE', sa.Float(), nullable=True),
    sa.Column('WBI', sa.Float(), nullable=True),
    sa.Column('WFMP', sa.Float(), nullable=True),
    sa.Column('ZPCN25_D', sa.Float(), nullable=True),
    sa.Column('ZT49_D', sa.Float(), nullable=True),
    sa.Column('ZTLA_D', sa.Float(), nullable=True),
    sa.Column('ZTNAC_D', sa.Float(), nullable=True),
    sa.Column('ZWF36_D', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Y_engine_id'), 'Y', ['engine_id'], unique=False)
    op.create_index(op.f('ix_Y_flight_datetime'), 'Y', ['flight_datetime'], unique=False)
    op.create_index(op.f('ix_Y_flight_phase'), 'Y', ['flight_phase'], unique=False)
    op.create_index(op.f('ix_Y_id'), 'Y', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Y_id'), table_name='Y')
    op.drop_index(op.f('ix_Y_flight_phase'), table_name='Y')
    op.drop_index(op.f('ix_Y_flight_datetime'), table_name='Y')
    op.drop_index(op.f('ix_Y_engine_id'), table_name='Y')
    op.drop_table('Y')
    # ### end Alembic commands ###
